export default {
  bgPattern: require('../assets/drawer-cover.jpeg'),
  user: require('../assets/user.jpg'),
  logo: require('../assets/icons/icon.png'),
  img1: require('../assets/images/1.jpg'),
  img2: require('../assets/images/2.jpg'),
  img3: require('../assets/images/3.jpg'),
  img4: require('../assets/images/4.jpg'),
  img5: require('../assets/images/5.jpg'),
  img6: require('../assets/images/6.jpg'),
  img7: require('../assets/images/7.jpg'),
  img8: require('../assets/images/8.jpg'),
  img9: require('../assets/images/9.jpg'),
  img11: require('../assets/images/11.jpg'),
  img13: require('../assets/images/13.jpg'),
  img14: require('../assets/images/14.jpeg'),
  img0: require('../assets/images/0.jpeg'),
  avatar: require('../assets/images/ava.jpg'),
  empty: require('../assets/images/empty.png'),
  tap: require('../assets/images/logotap.png'),

  welcome1:require('../assets/images/img1.png'),
  en:require('../assets/images/en.jpg'),
  welcome2:require('../assets/images/img2.png'),
  product: require('../assets/images/product.png'),
  bg:require('../assets/images/bg.png'),
  prod:require('../assets/images/products.png'),
  stock:require('../assets/images/stock.png'),
  report:require('../assets/images/report.png'),
  ventes:require('../assets/images/achat.png'),
  purshase:require('../assets/images/purshase.png'),
  pie:require('../assets/images/pie.png'),
};
