const lang = {
    fr:{
        welcome:'Bienvenu sur',
        francais:'Français',
        anglais:'Anglais',
        welcomeAuth:'Bienvenu',
        kiswahili:'Kiswahili',
        shoose:"Choisissez une langue avant de continuer",
        continuer:'Continuer',
        token:"Veuillez entrer votre token d'authentification pour continuer",
        logText:"Veuillez vous connecter à l'aide de votre numéro de téléphone ou bien votre adresse email pour continuer",
        email:"Votre adresse email",
        password:"Votre mot de passe",
        forgot:"Mot de passe oublié ?",
        login:"Se connecter",
        invoice:"Factures",
        home:"Accueil",
        category:"Catégories",
        cart:"Panier",
        pos:"P.O.S",
        settings:"Réglages",
        langue:"Langue",
        theme:"Thème",
        clair:"Clair",
        sombre:"Sombre",
        print:"Imprimante",
        printMsg:"Cliquer ici pour configurer une imprimante",
        devise:"Devise",
        deviseMsg:"Cliquer ici pour changer la devise",
        logout:"Se déconnecter",
        register:'Créer un compte',
        userName:'Nom d\'utilisatreur',
        userNamePhone:"Nom d\'utilisatreur ou phone"

       
    },
    en:{
        welcome:'Welcome to',
        francais:'French',
        anglais:'English',
        kiswahili:'Kiswahili',
        shoose:"Choose a language before continuing",
        continuer:'Continue',
        token:"Please enter your authentication token to continue",
        logText:"Please enter your credentials to continue",
        email:"Your email address",
        password:"Your password",
        forgot:"Forgot password ?",
        login:"Login",
        welcomeAuth:'Welcome',
        invoice:"Invoices",
        home:"Home",
        category:"Categories",
        cart:"Cart",
        pos:"P.O.S",
        settings:"Settings",
        langue:"Language",
        theme:"Theme",
        sombre:"Dark",
        printMsg:"Click here to configure a printer",
        print:"Printer",
        clair:"Light",
        devise:"Currency",
        register:'Register',
        deviseMsg:"Click here to change currency",
        logout:"Logout",
        userName:"Username",
        userNamePhone:"username or phone number"

    },
    ks:{
        welcome:'Karibu kwenye',
        francais:'Kifaransa',
        anglais:'Kingereza',
        kiswahili:'Kiswahili',
        shoose:"Chagua lugha kabla ya kuendelea",
        continuer:'Endelea',
        token:"Tafadhali weka tokeni yako ya uthibitishaji ili kuendelea",
        logText:"Tafadhali weka kitambulisho chako ili kuendelea",
        email:"Barua pepe yako",
        password:"Nenosiri lako",
        forgot:"Umesahau nywila ?",
        login:"Ingia",
        invoice:"Ankara",
        home:"Karibu",
        category:"kategoria",
        cart:"Kikapu",
        pos:"P.O.S",
        settings:"Mipangilio",
        langue:"Luga",
        theme:"mandhari",
        register:'Funguwa akaunti',
        welcomeAuth:'Karibu',
        sombre:"Giza",
        clair:"Wangaza",
        printMsg:"Finya hapa ili kusanidi kichapishi",
        print:"Printa",
        devise:"Sarafu",
        deviseMsg:"Finya hapa ili kubadilisha sarafu",
        logout:"Kuondoka",
        userName:"jina la mtumiaji",
        userNamePhone:"jina la mtumiaji au namba ya sim"
    }
}

export default lang