export default {
  LOGIN: 'Login',
  WELCOME: 'Welcome',
  REGISTER: 'Register',
  ONBOARDING: 'Onboarding',
  FORGOT_PASSWORD: 'Forgot Password',
  TOKEN: 'Token',
  LANGUE: 'Langue',
  PAY_CASH:'Pay_cash',
  INVOICE_DETAILS: 'Invoices details',
  ADD_ENTREPRISE:'Add_entreprise',
  OPERATIONS: 'Operations',
  QR: 'Qr',
  OTP:'Otp',
  SHOOSE: 'Shose',
  CATEGORIES:'Categories',
  CATEGORIE_DETAIL:'Categories detail',
  INVOICES: 'Invoices',
  ACHAT:'Achat',
  VENTES: 'Ventes',
  PRODUCT_LIST: 'Product List',
  STOCK: 'Stock',
  PRODUCT_DETAILS: 'Product Details',
  DEPENSES: 'Depends',
  RAPPORTS: 'Rapports',
  SOCKET: 'Socket',

  HOME: 'Home',
  HOME_TAB: 'Home Tab',
  HOME_DRAWER: 'Home Drawer',
  LIST_ENTREPRISE:'List Entreprise',
  EDIT_ENTREPRISE:'Edit Entreprise',

  CART: 'Cart',
  CART_NAVIGATOR: 'Cart Navigator',
  WALLET_DRAWER: 'Wallet Drawer',

  ADD_USER:'Add User',
  USER_LIST: 'User List',

  NOTIFICATIONS: 'Notifications',
  NOTIFICATIONS_DRAWER: 'Notifications Drawer',

  SETTINGS: 'Settings',
  ACCOUNT_SETTINGS: 'Account Settings',
  SETTINGS_NAVIGATOR: 'Settings Navigator',
  OPERATION_DETAIL: 'Operation Detail',

  SETTINGS_DETAIL: 'Settings Detail',
  PROFILE: 'My Profile',
};
